classDiagram
    class Usuario {
        +int id
        +String nome
        +String email
        +consultarEmprestimos()
    }

    class Bibliotecario {
        +String matricula
        +registrarEmprestimo()
        +registrarDevolucao()
    }

    class Livro {
        +String isbn
        +String titulo
        +String autor
        +consultarDisponibilidade()
    }

    class Exemplar {
        +int tombo
        +String estado
        +boolean disponivel
    }

    class Emprestimo {
        +Date dataEmprestimo
        +Date dataDevolucao
        +String status
        +float multa
        +calcularMulta()
        +devolver()
    }

    Bibliotecario --|> Usuario : heranca
    Usuario "1" --> "*" Emprestimo : realiza
    Livro "1" --> "*" Exemplar : possui
    Emprestimo "*" --> "1" Exemplar : referencia
    Emprestimo "*" --> "1" Usuario : atende
