architecture-beta
    group ui[UI]
    group dominio[Dominio]
    group infra[Infraestrutura]

    service app[App] in ui
    service web[Web] in ui

    service pedidos[Pedidos] in dominio
    service entregas[Entregas] in dominio
    service pagamentos[Pagamentos] in dominio

    service db[DB] in infra
    service cache[Cache] in infra

    app:R --> L:web
    app:B --> T:pedidos
    web:B --> T:pedidos
    pedidos:B --> T:pagamentos
    pedidos:R --> L:entregas
    pagamentos:B --> T:db
    entregas:B --> T:db
    db:R --> L:cache
